DROP ALL OBJECTS;
CREATE TABLE genres (
id INTEGER PRIMARY KEY,
name varchar
);

CREATE TABLE rating (
id INTEGER PRIMARY KEY,
name varchar
);

CREATE TABLE users (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
email varchar NOT NULL,
login varchar NOT NULL,
name varchar DEFAULT 'noname',
birthday timestamp
);

CREATE TABLE films (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar NOT NULL,
description varchar,
rating_id INTEGER ,
release_date timestamp,
duration INTEGER
);

CREATE TABLE likes (
user_id INTEGER REFERENCES users (id),
film_id INTEGER REFERENCES films (id)
);

CREATE TABLE friendship (
user_id INTEGER REFERENCES users (id),
friend_id INTEGER REFERENCES users (id),
confirmed_friend boolean DEFAULT false,
PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE film_genres(
    film_id  BIGINT  NOT NULL REFERENCES films (id),
    genre_id INTEGER NOT NULL REFERENCES genres (id)
);