CREATE TABLE users (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar NOT NULL,
login varchar NOT NULL,
name varchar DEFAULT 'noname',
birthday timestamp
);

CREATE TABLE likes (
user_id INTEGER REFERENCES users (id),
film_id INTEGER REFERENCES films (id)
);

CREATE TABLE friendship (
user_id INTEGER PRIMARY KEY REFERENCES users (id),
friend_id INTEGER REFERENCES users (id),
confirmedFriend boolean DEFAULT false
);

CREATE TABLE films (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar NOT NULL,
description varchar(264),
genre_id INTEGER REFERENCES genres (id),
rating_id INTEGER REFERENCES rating (id),
release_date timestamp,
duration timestamp
);

CREATE TABLE genres (
id INTEGER PRIMARY KEY ,
title varchar
);

CREATE TABLE rating (
id INTEGER PRIMARY KEY ,
title varchar
);